MAX_X = 0
MAX_Y = 0

REFRESH_RATE = 0.01 #60fps
RELEASE_SNAPBUFFER = 0.1

DEFAULT_WINDOW_X = 10
DEFAULT_WINDOW_Y = 10

MIN_WINDOW_X = 10
MIN_WINDOW_Y = 5


TASKBAR_HEIGHT = 4
TASKBAR_WIDTH = MAX_Y

TASKBAR_OFFSET_Y = 0 # use negative values to go down 
TASKBAR_OFFSET_X = 0 # use neg values

#Not used
# DOUBLE_CLICK_RELEASE_INTERVAL = 0.05
# FLUSH_INPUT_INTERVAL = 0.5